name: poke_magic
description: PokÃ©dex.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"


flutter:
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne.ttf

  uses-material-design: true
  assets:
    - assets/data/pokedex.json
    - assets/data/evolution.json

# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon.png"