name: poke_magic
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  # path_provider: ^1.1.0
  http: ^0.12.0+2
  pokeapi: any
  cached_network_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"


flutter:
  # fonts:
  #   - family: Special
  #     fonts:
  #       - asset: assets/fonts/SpecialElite.ttf

  uses-material-design: true
  # assets:
  #   - assets/images/icons/iniciar.png

# flutter_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/icon.png"